-- drop
DROP TABLE "Vaccine_package" CASCADE CONSTRAINTS;
DROP TABLE "Package_delivery" CASCADE CONSTRAINTS;
DROP TABLE "Addressee" CASCADE CONSTRAINTS;
DROP TABLE "Vaccine_shot" CASCADE CONSTRAINTS;
DROP TABLE "Vaccination_centre" CASCADE CONSTRAINTS;
DROP TABLE "Reported_side_effect" CASCADE CONSTRAINTS;
DROP TABLE "Person" CASCADE CONSTRAINTS;
DROP TABLE "Warehouse" CASCADE CONSTRAINTS;
DROP TABLE "Side_effect_type" CASCADE CONSTRAINTS;
DROP TABLE "Appointment" CASCADE CONSTRAINTS;
DROP TABLE "Vaccine" CASCADE CONSTRAINTS;
DROP TABLE "Doctor" CASCADE CONSTRAINTS;
DROP TABLE "Patient" CASCADE CONSTRAINTS;
DROP TABLE "Address" CASCADE CONSTRAINTS;
DROP TABLE "Manufacturer" CASCADE CONSTRAINTS;
DROP TABLE "Distributor" CASCADE CONSTRAINTS;

